Ankiety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls')),
    path('formularze/', include('formularze.urls')),
    path('admin/', admin.site.urls),

]

formularze/urls.py
from django.urls import path
from . import views


app_name = 'formularze'
urlpatterns = [
    path('', views.ListaPytan.as_view(), name='lista-pytan'),
    path('pytanie/glosuj/<int:pid>', views.pytanie_glosuj, name='pytanie-glosuj'),
    path('pytanie/<int:pk>', views.LiczbaGlosow.as_view(), name='liczba-glosow'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
	path('', views.index, name='index'),
    path('rejestruj/', views.rejestruj, name='rejestruj'),
    path('loguj/', views.loguj_user, name='loguj'),
    path('wyloguj/', views.wyloguj_user, name='wyloguj'),
]

formularze/models.py
from django.db import models
from django.utils import timezone

class Kategoria(models.Model):
    nazwa = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'kategorie'

    def __str__(self):
        return self.nazwa


class Pytanie(models.Model):
    kategoria = models.ForeignKey(Kategoria, on_delete=models.SET_NULL,
                                  blank=True, null=True, related_name="pytania")
    tekst_pytania = models.CharField('tekst pytania', max_length=200)
    data_d = models.DateTimeField('data dodania', default=timezone.now)

    class Meta:
        verbose_name_plural = 'pytania'
        ordering = ['-data_d', ]

    def __str__(self):
        return self.tekst_pytania[0:50]


class Odpowiedz(models.Model):
    pytanie = models.ForeignKey(Pytanie, on_delete=models.CASCADE)
    tekst_odpowiedzi = models.CharField('tekst odpowiedzi', max_length=200)
    glosy = models.IntegerField('liczba głosów', default=0)

    class Meta:
        verbose_name_plural = 'odpowiedzi'

    def __str__(self):
        return self.tekst_odpowiedzi[0:50]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms

class UserLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    haslo = forms.CharField(
        label="Twoje hasło",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'})
    )

formularze/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from formularze.models import Pytanie, Odpowiedz

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse


class ListaPytan(ListView):
    model = Pytanie
    template_name = 'formularze/lista_pytan.html'
    context_object_name = 'pytania'

    def get_queryset(self):
        return Pytanie.objects.order_by('-data_d')[:10]


class LiczbaGlosow(DetailView):
    model = Pytanie
    template_name = 'formularze/liczba_glosow.html'
    context_object_name = 'pytanie'


@login_required()
def pytanie_glosuj(request, pid):
    pytanie = get_object_or_404(Pytanie, pk=pid)
    if request.method == 'POST':
        try:
            odpowiedz = pytanie.odpowiedz_set.get(pk=request.POST['odpowiedz'])
        except (KeyError, Odpowiedz.DoesNotExist):
            return render(request, 'formularze/pytanie_glosuj.html', {
                'pytanie': pytanie,
                'komunikat_bledu': 'Nie wybrałeś odpowiedzi!',
            })
        else:
            odpowiedz.glosy += 1
            odpowiedz.save()
            return redirect(reverse('formularze:liczba-glosow', args=(pytanie.id,)))
    else:
        return render(request, 'formularze/pytanie_glosuj.html', {'pytanie': pytanie})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from users.forms import UserLoginForm

def index(request):
    return render(request, 'users/index.html')

def rejestruj(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Utworzono konto! Możesz się zalogować!")
            return redirect(reverse('users:index'))
    else:
        form = UserCreationForm()

    kontekst = {'form': form}
    return render(request, 'users/rejestruj.html', kontekst)


def loguj_user(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            nazwa = form.cleaned_data['login']
            haslo = form.cleaned_data['haslo']
            user = authenticate(request, username=nazwa, password=haslo)
            if user is not None:
                login(request, user)
                messages.success(request, "Zostałeś zalogowany")
                return redirect(reverse('users:index'))
            else:
                messages.error(request, "Błędny login lub hasło")

    else:
        form = UserLoginForm()

    kontekst = {'form': form}
    return render(request, 'users/loguj_user.html', kontekst)

def wyloguj_user(request):
    logout(request)
    messages.info(request, "Zostałeś wylogowany")
    return redirect(reverse('users:index'))

formularze/templates/formularze/liczba_glosow.html
{% extends 'szablon.html' %}

{% block tresc %}
    <h2>Głosy</h2>
    <h3>{{ pytanie }}</h3>
    <ol>
    {% for o in pytanie.odpowiedz_set.all %}
        <li class="mb-1">
            <span class="lead">{{ o }}, głosów:</span>
            <span class="badge badge-secondary">{{ o.glosy }}&nbsp;</span>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

formularze/templates/formularze/lista_pytan.html
{% extends 'szablon.html' %}

{% block tresc %}
    <h2>Lista pytań</h2>
    <ul>
    {% for p in pytania %}
        <li class="mb-1">
            <span class="lead">{{ p }}</span>
            <a href="{% url 'formularze:pytanie-glosuj' p.id %}" class="btn btn-secondary btn-sm">Głosuj</a>
            <br>
            <span class="float-right">(kategoria: {{ p.kategoria.nazwa }})</span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

formularze/templates/formularze/pytanie_glosuj.html
{% extends 'szablon.html' %}

{% block tresc %}
    <h2>Oddaj głos</h2>
    <div class="mx-3">
        <h3>{{ pytanie }}</h3>

        {% if komunikat_bledu %}
            <div class="text-warning bg-secondary rounded p-3">
                Błąd: {{ komunikat_bledu }}
            </div>
        {% endif %}

        <form action="{% url 'formularze:pytanie-glosuj' pytanie.id %}" method="post">
            {% csrf_token %}
            <ul class="list-unstyled">
                {% for o in pytanie.odpowiedz_set.all %}
                <li class="mb-1">
                    <input type="radio" name="odpowiedz" id="o{{ forloop.counter }}" value="{{ o.id }}">
                    <label for="o{{ forloop.counter }}">{{ o.tekst_odpowiedzi }}</label>
                </li>
                {% endfor %}
            </ul>
            <button type="submit" class="btn btn-secondary">Głosuj</button>
        </form>

    </div>


    <ul>
    {% for p in pytania %}
        <li class="mb-1">
            <span class="lead">{{ p }}</span>
            <br>
            <span class="float-right">(kategoria: {{ p.kategoria.nazwa }})</span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}ANKIETY{% endblock tytul %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" >Serwis ANKIETY</a>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Formularze</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'formularze:lista-pytan' %}" class="dropdown-item">Lista pytań</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Użytkownik</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'users:index' %}" class="dropdown-item">Strona główna</a>
                        {% if not user.is_authenticated %}
                            <a href="{% url 'users:rejestruj' %}" class="dropdown-item">Załóż konto</a>
                            <a href="{% url 'users:loguj' %}" class="dropdown-item">Zaloguj</a>
                        {% else %}
                            <a href="{% url 'users:wyloguj' %}" class="dropdown-item">Wyloguj</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>{% block naglowek %}Projekt Django{% endblock naglowek %}</h1>
                {% block komunikaty %}
                {% if messages %}
                    <ul>
                    {% for komunikat in messages %}
                        <li>{{ komunikat }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                {% endblock komunikaty %}
                {% block tresc %}
                {% endblock tresc %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/index.html
{% extends 'szablon.html' %}

{% block tytul %}Użytkownicy{% endblock tytul %}

{% block naglowek %}<br> Witaj wśród użytkowników serwisu Ankiety!{% endblock naglowek %}

{% block tresc %}
    <br>
    <p>Nasz serwis bawi i uczy!</p>
{% endblock tresc %}

users/templates/users/loguj_user.html
{% extends 'szablon.html' %}
{% block naglowek %}Logowanie{% endblock naglowek %}
{% block tresc %}

    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}.</p>
    {% else %}
        <form action=".." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zaloguj</button>
        </form>
    {% endif %}

{% endblock tresc %}

users/templates/users/rejestruj.html
{% extends 'szablon.html' %}
{% block naglowek %}Rejestracja{% endblock naglowek %}
{% block tresc %}

    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}.</p>
    {% else %}
        <form action=".." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zarejestruj</button>
        </form>
    {% endif %}

{% endblock tresc %}